# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name:  mvn verify linux

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '15 3 1 * *'  # <https://crontab.guru/#45_16_*_*_0> 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17','20']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
